/// This file must keep synchronized with the one in the gpusynth repo.

syntax = "proto3";
package torch.profiler.gpusynth;

/// The (de)-serialization is handled by user themselves.
message CudaCall {
  bytes payload = 1;
}

// enum TorchValueType {
//   TENSOR = 0;
//   TUPLE = 1;
//   List = 2;
//   Double = 3;
//   Int = 4;
//   Bool = 5;
//   String = 6;
//   Device = 7;
// }
message TorchValue {
  message Tensor {
    repeated int64 shape = 1;
    int32 dtype = 2;
    string device = 3;
  }
  message Tuple {
    repeated TorchValue elements = 1;
  }
  message List {
    repeated TorchValue elements = 1;
  }
  message Double {
    double value = 1;
  }
  message Int {
    int64 value = 1;
  }
  message Bool {
    bool value = 1;
  }
  message String {
    string value = 1;
  }
  message Device {
    string value = 1;
  }
  // TorchValueType type = 1;
  oneof oneof {
    Tensor tensor = 1;
    Tuple tuple = 2;
    List list = 3;
    Double double = 4;
    Int int = 5;
    Bool bool = 6;
    String string = 7;
    Device device = 8;
  }
}

message TorchCall {
  message CudaStream {
    /// Device id
    int32 device = 1;
    /// Stream id
    int32 id = 2;
  }

  enum CallPhase {
    BEGIN = 0;
    END = 1;
  }

  /// Pre-filled values
  int32 pid = 1;
  int32 tid = 2;
  string hostname = 3;
  /// Per-call variant values
  CudaStream stream = 4;
  int64 cur_sim_time = 5;
  /// Function name
  string name = 6;
  /// Begin or end of the function call
  CallPhase phase = 7;
  /// Function arguments
  // repeated string args = 8;
  repeated TorchValue args = 8;
}

// message TorchCallBatch {
//   repeated TorchCall calls = 1;
// }

message ExitRequest {
  int32 pid = 1;
  int32 tid = 2;
  string hostname = 3;
  int64 cur_sim_time = 4;
}

message VoidResponse {
}

message SyncResponse {
  int64 end_time = 1;
}

message EventResult {
  optional int64 end_time = 1;
}

message StreamResult {
  bool completed = 1;
}

message NcclId {
  bytes content = 1;
}

service GpuSynth {
  rpc cuda(CudaCall) returns (VoidResponse);
  rpc torch(TorchCall) returns (VoidResponse);
  rpc bye(ExitRequest) returns (VoidResponse);
  // rpc torch_batch(TorchCallBatch) returns (VoidResponse);

  rpc cuda_sync(CudaCall) returns (SyncResponse);
  rpc cuda_event_query(CudaCall) returns (EventResult);
  rpc cuda_stream_query(CudaCall) returns (StreamResult);
  rpc nccl_get_unique_id(CudaCall) returns (NcclId);
}